version: "3.10"
services:
  home-dns:
    container_name: strefakursow-dns
    image: index.docker.io/piotrskoska/strefakursow-dns:${ARCH_TYPE}
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    restart: unless-stopped
